[project]
name = "roach"
version = "0.0.1"
description = "Experiment management framework for ML and data science"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
pytorch = ">=2.0"
matplotlib = ">=3.5"
seaborn = ">=0.12"
pandas = ">=1.5"
psutil = ">=5.9"
pip = ">=23.0"

[tasks]
install-roach = "pip install -e ."
test-ml-workflow = "python examples/ml_workflow.py"
test-queue-demo = "python examples/queue_demo.py"
test-plotting-demo = "python examples/plotting_demo.py"
test-all = "bash examples/run_all.sh"
