#!/bin/bash
# Generated by roach.slurm.submit -- piped to sbatch on stdin, so slurm keeps its
# own copy and nothing has to live on shared storage. Placeholders are filled in
# by submit(); everything here is deliberately the same for every job.
set -euo pipefail

echo "=== $(date -Is) job $SLURM_JOB_ID on $(hostname), restarts=${SLURM_RESTART_COUNT:-0} ==="
echo "repo=@REPO@ commit=@COMMIT@ run_id=@RUN_ID@ target=@TARGET@"

export USER=${USER:-$(id -un)}
export TMPDIR=/tmp/$USER
mkdir -p "@CLONE_ROOT@"

# The job runs the commit that was submitted, not whatever main has become. The
# clone is the one step that cannot come from the package: the package is what
# we are about to clone.
WORK_DIR=$(mktemp -d "@CLONE_ROOT@/@NAME@-@RUN_ID@-job${SLURM_JOB_ID}.XXXX")
trap 'rm -rf "$WORK_DIR"' EXIT   # the pixi env lives in the clone, so it goes too
git -c url."https://x-access-token:$(tr -d '[:space:]' < "@SECRETS_DIR@/github")@github.com/".insteadOf="https://github.com/" \
    clone --quiet "@REPO@" "$WORK_DIR/repo"
cd "$WORK_DIR/repo"
git checkout --quiet "@COMMIT@"
echo "clone: $PWD @ $(git rev-parse --short HEAD)"

# Node-local home, caches and tokens; sets the node up if it has never been
# used. Spliced in rather than sourced from a path: this runs before the
# environment exists, so roach is not importable yet, and inlining also pins the
# node setup to the submission instead of to whatever is installed later.
@ENV@

# pixi.lock is gitignored, so a fresh clone has none and the first job of a run
# solves the environment itself. Keep that solve with the run and reuse it on
# every requeue, so the environment cannot drift between attempts.
RUN_LOCK=@LOG_ROOT@/@RUN_ID@.pixi.lock
if [[ -f $RUN_LOCK ]]; then
    echo "reusing pixi.lock from $RUN_LOCK"
    cp "$RUN_LOCK" pixi.lock
fi
pixi install
[[ -f $RUN_LOCK ]] || cp pixi.lock "$RUN_LOCK"

# Whatever this project needs built before its ranks start (@SETUP@ is the
# submitter's  argument; empty is fine).
@SETUP@

# One task per GPU: each rank is a slurm task, so slurm's preemption SIGTERM
# reaches every rank directly. They save resume.pt at the next step boundary and
# exit; this script only has to outlive them, hence the ignored trap. Slurm
# requeues the job itself, and the run id is fixed, so the next attempt resumes.
trap '' TERM USR1
# --export=ALL here is not the same as sbatch's: that one kept the *submit
# shell* out of the job, this one lets the tasks inherit the environment this
# script just built. Without it srun starts them nearly empty (--export=NONE
# sets SLURM_EXPORT_ENV=NONE) and they find neither pixi nor the tokens, caches
# and node-local HOME that env.sh set up.
srun --export=ALL --label --kill-on-bad-exit=1 \
    pixi run python -m roach.slurm.run "@TARGET@" "@ARGS@" &
wait $!
